version: "3"
services:
  pg:
    image: "postgres:14.5"
    # build: .docker
    restart: always
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=""
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./create-db.sh:/docker-entrypoint-initdb.d/01-creeate-db.sh
    shm_size: "256MB"
volumes:
  pg_data: