version: "3"
services:
  pg:
    # container_name: "pg_fasthtmx"
    # image: "postgres:14.5-bullseye"
    build: .docker
    restart: always
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=""
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pgdata:/var/lib/postgresql/data
    shm_size: "256MB"
volumes:
  pg_data: