# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.2.0
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.kubernetes.cri-o.ContainerType/gallantmahavira: container
    io.kubernetes.cri-o.SandboxID/gallantmahavira: 3b50417d4562c1eb47c41d68da59c83f3150004ca7d56920aff5e57966f05bb
    io.kubernetes.cri-o.TTY/gallantmahavira: "false"
    io.podman.annotations.autoremove/gallantmahavira: "FALSE"
    io.podman.annotations.init/gallantmahavira: "FALSE"
    io.podman.annotations.privileged/gallantmahavira: "FALSE"
    io.podman.annotations.publish-all/gallantmahavira: "FALSE"
  creationTimestamp: "2022-09-07T14:19:31Z"
  labels:
    app: pg-pod
  name: pg-pod
spec:
  containers:
  - args:
    - postgres
    env:
    - name: POSTGRES_USER
      value: postgres
    - name: POSTGRES_HOST_AUTH_METHOD
      value: trust
    image: docker.io/library/postgres:14.5
    name: gallantmahavira
    ports:
    - containerPort: 5432
      hostPort: 15432
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: 954c7387f3364de7af3eeb01190d31fa6642611fdd93b92b90235d63c35569d9-pvc
  hostname: pg-pod
  restartPolicy: Always
  volumes:
  - name: 954c7387f3364de7af3eeb01190d31fa6642611fdd93b92b90235d63c35569d9-pvc
    persistentVolumeClaim:
      claimName: 954c7387f3364de7af3eeb01190d31fa6642611fdd93b92b90235d63c35569d9
status: {}

