version: "3"
services:
  pg:
    # container_name: "pg_fasthtmx"
    image: "postgres:14.5-bullseye"
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chinook
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pg_data: